name = "htpi"
defaultTargets = ["HTPILib"]

[leanOptions]
linter.unusedVariables = false
pp.funBinderTypes = true

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.8.0"

[[lean_lib]]
name = "HTPILib"
