name = "htpi"
defaultTargets = ["HTPILib"]

moreGlobalServerArgs = ["-Dlinter.unusedVariables=false", "-Dpp.funBinderTypes=true"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.8.0"

[[lean_lib]]
name = "HTPILib"
